#ifndef ODRVIOLATIONCHECKDEMOLIBRARY_ODRVIOLATIONCHECKDEMOLIBRARY_H
#define ODRVIOLATIONCHECKDEMOLIBRARY_ODRVIOLATIONCHECKDEMOLIBRARY_H
#include <cstdio>

#ifdef ODRVIOLATIONCHECKDEMO_FLAG
#define ODRVIOLATIONCHECKDEMO_MACRO(text) printf("%s\n", text);
#else
#define ODRVIOLATIONCHECKDEMO_MACRO(text)
#endif

namespace ODRViolationCheckDemoLibrary
{

class ODRViolationCheckDemoLibrary
{
public:

	void HelloWorld()
	{
		ODRVIOLATIONCHECKDEMO_MACRO("Hello world");
	}

	void HelloWorld2();

};

}

#endif // ODRVIOLATIONCHECKDEMOLIBRARY_ODRVIOLATIONCHECKDEMOLIBRARY_H
